#!/usr/bin/bash
echo "Content-Type: text/html"
echo ""
echo "<html><body>"
echo "<h1>CGI/1.1 demo</h1>"
echo "<pre>"
echo "Method:      $REQUEST_METHOD"
echo "Path:        $PATH_INFO"
echo "Query:       $QUERY_STRING"
echo "Remote addr: $REMOTE_ADDR"
echo "Server:      $SERVER_SOFTWARE"
echo "Date:        $(date -u)"
echo "</pre>"
echo "</body></html>"
